// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0
// 	protoc        v3.13.0
// source: netcluster/message.proto

package netcluster

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Master_PublishServerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId                 uint32 `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	ServerType               uint32 `protobuf:"varint,2,opt,name=ServerType,proto3" json:"ServerType,omitempty"`
	IsConnected              bool   `protobuf:"varint,3,opt,name=IsConnected,proto3" json:"IsConnected,omitempty"`
	IsWorking                bool   `protobuf:"varint,4,opt,name=IsWorking,proto3" json:"IsWorking,omitempty"`
	DisableNewConsistentFLow bool   `protobuf:"varint,5,opt,name=DisableNewConsistentFLow,proto3" json:"DisableNewConsistentFLow,omitempty"`
}

func (x *Master_PublishServerStatus) Reset() {
	*x = Master_PublishServerStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Master_PublishServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Master_PublishServerStatus) ProtoMessage() {}

func (x *Master_PublishServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Master_PublishServerStatus.ProtoReflect.Descriptor instead.
func (*Master_PublishServerStatus) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{0}
}

func (x *Master_PublishServerStatus) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *Master_PublishServerStatus) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *Master_PublishServerStatus) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *Master_PublishServerStatus) GetIsWorking() bool {
	if x != nil {
		return x.IsWorking
	}
	return false
}

func (x *Master_PublishServerStatus) GetDisableNewConsistentFLow() bool {
	if x != nil {
		return x.DisableNewConsistentFLow
	}
	return false
}

type Slave_ReportLoadLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFix     bool   `protobuf:"varint,1,opt,name=isFix,proto3" json:"isFix,omitempty"`
	AServerID uint32 `protobuf:"varint,2,opt,name=AServerID,proto3" json:"AServerID,omitempty"`
	BServerID uint32 `protobuf:"varint,3,opt,name=BServerID,proto3" json:"BServerID,omitempty"`
}

func (x *Slave_ReportLoadLevel) Reset() {
	*x = Slave_ReportLoadLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slave_ReportLoadLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_ReportLoadLevel) ProtoMessage() {}

func (x *Slave_ReportLoadLevel) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_ReportLoadLevel.ProtoReflect.Descriptor instead.
func (*Slave_ReportLoadLevel) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{1}
}

func (x *Slave_ReportLoadLevel) GetIsFix() bool {
	if x != nil {
		return x.IsFix
	}
	return false
}

func (x *Slave_ReportLoadLevel) GetAServerID() uint32 {
	if x != nil {
		return x.AServerID
	}
	return 0
}

func (x *Slave_ReportLoadLevel) GetBServerID() uint32 {
	if x != nil {
		return x.BServerID
	}
	return 0
}

type Master_PublishLoadLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoadLevel uint32 `protobuf:"varint,1,opt,name=LoadLevel,proto3" json:"LoadLevel,omitempty"`
}

func (x *Master_PublishLoadLevel) Reset() {
	*x = Master_PublishLoadLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Master_PublishLoadLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Master_PublishLoadLevel) ProtoMessage() {}

func (x *Master_PublishLoadLevel) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Master_PublishLoadLevel.ProtoReflect.Descriptor instead.
func (*Master_PublishLoadLevel) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{2}
}

func (x *Master_PublishLoadLevel) GetLoadLevel() uint32 {
	if x != nil {
		return x.LoadLevel
	}
	return 0
}

type Slave_ReqShiftFixMaster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasterID  uint32 `protobuf:"varint,1,opt,name=MasterID,proto3" json:"MasterID,omitempty"`
	AServerID uint32 `protobuf:"varint,2,opt,name=AServerID,proto3" json:"AServerID,omitempty"`
	BServerID uint32 `protobuf:"varint,3,opt,name=BServerID,proto3" json:"BServerID,omitempty"`
}

func (x *Slave_ReqShiftFixMaster) Reset() {
	*x = Slave_ReqShiftFixMaster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slave_ReqShiftFixMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_ReqShiftFixMaster) ProtoMessage() {}

func (x *Slave_ReqShiftFixMaster) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_ReqShiftFixMaster.ProtoReflect.Descriptor instead.
func (*Slave_ReqShiftFixMaster) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{3}
}

func (x *Slave_ReqShiftFixMaster) GetMasterID() uint32 {
	if x != nil {
		return x.MasterID
	}
	return 0
}

func (x *Slave_ReqShiftFixMaster) GetAServerID() uint32 {
	if x != nil {
		return x.AServerID
	}
	return 0
}

func (x *Slave_ReqShiftFixMaster) GetBServerID() uint32 {
	if x != nil {
		return x.BServerID
	}
	return 0
}

type Slave_RepShiftFixMaster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasterID  uint32 `protobuf:"varint,1,opt,name=MasterID,proto3" json:"MasterID,omitempty"`
	AServerID uint32 `protobuf:"varint,2,opt,name=AServerID,proto3" json:"AServerID,omitempty"`
	BServerID uint32 `protobuf:"varint,3,opt,name=BServerID,proto3" json:"BServerID,omitempty"`
}

func (x *Slave_RepShiftFixMaster) Reset() {
	*x = Slave_RepShiftFixMaster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slave_RepShiftFixMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_RepShiftFixMaster) ProtoMessage() {}

func (x *Slave_RepShiftFixMaster) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_RepShiftFixMaster.ProtoReflect.Descriptor instead.
func (*Slave_RepShiftFixMaster) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{4}
}

func (x *Slave_RepShiftFixMaster) GetMasterID() uint32 {
	if x != nil {
		return x.MasterID
	}
	return 0
}

func (x *Slave_RepShiftFixMaster) GetAServerID() uint32 {
	if x != nil {
		return x.AServerID
	}
	return 0
}

func (x *Slave_RepShiftFixMaster) GetBServerID() uint32 {
	if x != nil {
		return x.BServerID
	}
	return 0
}

type Slave_ReqVerifyConfigFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileMd5 string `protobuf:"bytes,1,opt,name=FileMd5,proto3" json:"FileMd5,omitempty"`
}

func (x *Slave_ReqVerifyConfigFile) Reset() {
	*x = Slave_ReqVerifyConfigFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slave_ReqVerifyConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_ReqVerifyConfigFile) ProtoMessage() {}

func (x *Slave_ReqVerifyConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_ReqVerifyConfigFile.ProtoReflect.Descriptor instead.
func (*Slave_ReqVerifyConfigFile) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{5}
}

func (x *Slave_ReqVerifyConfigFile) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

type Master_ReqVerifyConfigFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileMd5       string `protobuf:"bytes,1,opt,name=FileMd5,proto3" json:"FileMd5,omitempty"`
	Time          int64  `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
	ReqServerId   uint32 `protobuf:"varint,3,opt,name=ReqServerId,proto3" json:"ReqServerId,omitempty"`
	ReqServerType uint32 `protobuf:"varint,4,opt,name=ReqServerType,proto3" json:"ReqServerType,omitempty"`
}

func (x *Master_ReqVerifyConfigFile) Reset() {
	*x = Master_ReqVerifyConfigFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Master_ReqVerifyConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Master_ReqVerifyConfigFile) ProtoMessage() {}

func (x *Master_ReqVerifyConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Master_ReqVerifyConfigFile.ProtoReflect.Descriptor instead.
func (*Master_ReqVerifyConfigFile) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{6}
}

func (x *Master_ReqVerifyConfigFile) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *Master_ReqVerifyConfigFile) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Master_ReqVerifyConfigFile) GetReqServerId() uint32 {
	if x != nil {
		return x.ReqServerId
	}
	return 0
}

func (x *Master_ReqVerifyConfigFile) GetReqServerType() uint32 {
	if x != nil {
		return x.ReqServerType
	}
	return 0
}

type Slave_RepVerifyConfigFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSucc        bool   `protobuf:"varint,1,opt,name=IsSucc,proto3" json:"IsSucc,omitempty"`
	Time          int64  `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
	ReqServerId   uint32 `protobuf:"varint,3,opt,name=ReqServerId,proto3" json:"ReqServerId,omitempty"`
	ReqServerType uint32 `protobuf:"varint,4,opt,name=ReqServerType,proto3" json:"ReqServerType,omitempty"`
}

func (x *Slave_RepVerifyConfigFile) Reset() {
	*x = Slave_RepVerifyConfigFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slave_RepVerifyConfigFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_RepVerifyConfigFile) ProtoMessage() {}

func (x *Slave_RepVerifyConfigFile) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_RepVerifyConfigFile.ProtoReflect.Descriptor instead.
func (*Slave_RepVerifyConfigFile) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{7}
}

func (x *Slave_RepVerifyConfigFile) GetIsSucc() bool {
	if x != nil {
		return x.IsSucc
	}
	return false
}

func (x *Slave_RepVerifyConfigFile) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Slave_RepVerifyConfigFile) GetReqServerId() uint32 {
	if x != nil {
		return x.ReqServerId
	}
	return 0
}

func (x *Slave_RepVerifyConfigFile) GetReqServerType() uint32 {
	if x != nil {
		return x.ReqServerType
	}
	return 0
}

type Slave_UptConfigMd5 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileMd5 string `protobuf:"bytes,1,opt,name=FileMd5,proto3" json:"FileMd5,omitempty"`
}

func (x *Slave_UptConfigMd5) Reset() {
	*x = Slave_UptConfigMd5{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slave_UptConfigMd5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave_UptConfigMd5) ProtoMessage() {}

func (x *Slave_UptConfigMd5) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave_UptConfigMd5.ProtoReflect.Descriptor instead.
func (*Slave_UptConfigMd5) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{8}
}

func (x *Slave_UptConfigMd5) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

// gm命令slave准备停止服务(slave->slave)
type SS_CmdPrepareCloseServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SS_CmdPrepareCloseServer) Reset() {
	*x = SS_CmdPrepareCloseServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS_CmdPrepareCloseServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS_CmdPrepareCloseServer) ProtoMessage() {}

func (x *SS_CmdPrepareCloseServer) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS_CmdPrepareCloseServer.ProtoReflect.Descriptor instead.
func (*SS_CmdPrepareCloseServer) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{9}
}

// 我要准备关闭了 (slave->master)
type SM_ReqPrepareCloseMyself struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SM_ReqPrepareCloseMyself) Reset() {
	*x = SM_ReqPrepareCloseMyself{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SM_ReqPrepareCloseMyself) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SM_ReqPrepareCloseMyself) ProtoMessage() {}

func (x *SM_ReqPrepareCloseMyself) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SM_ReqPrepareCloseMyself.ProtoReflect.Descriptor instead.
func (*SM_ReqPrepareCloseMyself) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{10}
}

// slave->slave 通知关闭服务
type SS_CmdCloseServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SS_CmdCloseServer) Reset() {
	*x = SS_CmdCloseServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS_CmdCloseServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS_CmdCloseServer) ProtoMessage() {}

func (x *SS_CmdCloseServer) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS_CmdCloseServer.ProtoReflect.Descriptor instead.
func (*SS_CmdCloseServer) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{11}
}

// adminsvr 发送gm命令，让某些slave不再接入新用户的请求 （不影响旧用户，旧用户仍可以正常享有这些slave的服务）
type S2S_CmdUnloadServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2S_CmdUnloadServer) Reset() {
	*x = S2S_CmdUnloadServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2S_CmdUnloadServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2S_CmdUnloadServer) ProtoMessage() {}

func (x *S2S_CmdUnloadServer) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2S_CmdUnloadServer.ProtoReflect.Descriptor instead.
func (*S2S_CmdUnloadServer) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{12}
}

//  (slave->master) slave告知master，已经绑定“我”的旧用户的请求仍然交给”我“处理，但“我”不再接受新用户的请求，对新用户的请求做负载均衡的时候别把“我”算进去
type S2M_ReqUnloadMyself struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2M_ReqUnloadMyself) Reset() {
	*x = S2M_ReqUnloadMyself{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netcluster_message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2M_ReqUnloadMyself) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2M_ReqUnloadMyself) ProtoMessage() {}

func (x *S2M_ReqUnloadMyself) ProtoReflect() protoreflect.Message {
	mi := &file_netcluster_message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2M_ReqUnloadMyself.ProtoReflect.Descriptor instead.
func (*S2M_ReqUnloadMyself) Descriptor() ([]byte, []int) {
	return file_netcluster_message_proto_rawDescGZIP(), []int{13}
}

var File_netcluster_message_proto protoreflect.FileDescriptor

var file_netcluster_message_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6e, 0x65, 0x74, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6e, 0x65, 0x74, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0xd4, 0x01, 0x0a, 0x1a, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x49, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x69, 0x6e,
	0x67, 0x12, 0x3a, 0x0a, 0x18, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x65, 0x77, 0x43,
	0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x46, 0x4c, 0x6f, 0x77, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x18, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x65, 0x77, 0x43,
	0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x46, 0x4c, 0x6f, 0x77, 0x22, 0x69, 0x0a,
	0x15, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x4c, 0x6f, 0x61,
	0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x46, 0x69, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x46, 0x69, 0x78, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x41, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x42,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x22, 0x37, 0x0a, 0x17, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x5f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x22, 0x71, 0x0a, 0x17, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x52, 0x65, 0x71, 0x53, 0x68,
	0x69, 0x66, 0x74, 0x46, 0x69, 0x78, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x41, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x42, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x22, 0x71, 0x0a, 0x17, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x52, 0x65,
	0x70, 0x53, 0x68, 0x69, 0x66, 0x74, 0x46, 0x69, 0x78, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x41,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x41, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x42, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x22, 0x35, 0x0a, 0x19, 0x53, 0x6c, 0x61, 0x76, 0x65,
	0x5f, 0x52, 0x65, 0x71, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x64, 0x35, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x64, 0x35, 0x22, 0x92,
	0x01, 0x0a, 0x1a, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x52, 0x65, 0x71, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x46, 0x69, 0x6c, 0x65, 0x4d, 0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x52,
	0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x19, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x52, 0x65,
	0x70, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x55,
	0x70, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4d, 0x64, 0x35, 0x12, 0x18, 0x0a, 0x07, 0x46,
	0x69, 0x6c, 0x65, 0x4d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x69,
	0x6c, 0x65, 0x4d, 0x64, 0x35, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x53, 0x5f, 0x43, 0x6d, 0x64, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x4d, 0x5f, 0x52, 0x65, 0x71, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4d, 0x79, 0x73, 0x65, 0x6c, 0x66, 0x22, 0x13, 0x0a,
	0x11, 0x53, 0x53, 0x5f, 0x43, 0x6d, 0x64, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x32, 0x53, 0x5f, 0x43, 0x6d, 0x64, 0x55, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x32, 0x4d,
	0x5f, 0x52, 0x65, 0x71, 0x55, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x79, 0x73, 0x65, 0x6c, 0x66,
	0x42, 0x10, 0x5a, 0x0e, 0x6d, 0x78, 0x62, 0x2f, 0x6e, 0x65, 0x74, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_netcluster_message_proto_rawDescOnce sync.Once
	file_netcluster_message_proto_rawDescData = file_netcluster_message_proto_rawDesc
)

func file_netcluster_message_proto_rawDescGZIP() []byte {
	file_netcluster_message_proto_rawDescOnce.Do(func() {
		file_netcluster_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_netcluster_message_proto_rawDescData)
	})
	return file_netcluster_message_proto_rawDescData
}

var file_netcluster_message_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_netcluster_message_proto_goTypes = []interface{}{
	(*Master_PublishServerStatus)(nil), // 0: netcluster.Master_PublishServerStatus
	(*Slave_ReportLoadLevel)(nil),      // 1: netcluster.Slave_ReportLoadLevel
	(*Master_PublishLoadLevel)(nil),    // 2: netcluster.Master_PublishLoadLevel
	(*Slave_ReqShiftFixMaster)(nil),    // 3: netcluster.Slave_ReqShiftFixMaster
	(*Slave_RepShiftFixMaster)(nil),    // 4: netcluster.Slave_RepShiftFixMaster
	(*Slave_ReqVerifyConfigFile)(nil),  // 5: netcluster.Slave_ReqVerifyConfigFile
	(*Master_ReqVerifyConfigFile)(nil), // 6: netcluster.Master_ReqVerifyConfigFile
	(*Slave_RepVerifyConfigFile)(nil),  // 7: netcluster.Slave_RepVerifyConfigFile
	(*Slave_UptConfigMd5)(nil),         // 8: netcluster.Slave_UptConfigMd5
	(*SS_CmdPrepareCloseServer)(nil),   // 9: netcluster.SS_CmdPrepareCloseServer
	(*SM_ReqPrepareCloseMyself)(nil),   // 10: netcluster.SM_ReqPrepareCloseMyself
	(*SS_CmdCloseServer)(nil),          // 11: netcluster.SS_CmdCloseServer
	(*S2S_CmdUnloadServer)(nil),        // 12: netcluster.S2S_CmdUnloadServer
	(*S2M_ReqUnloadMyself)(nil),        // 13: netcluster.S2M_ReqUnloadMyself
}
var file_netcluster_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_netcluster_message_proto_init() }
func file_netcluster_message_proto_init() {
	if File_netcluster_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_netcluster_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Master_PublishServerStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slave_ReportLoadLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Master_PublishLoadLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slave_ReqShiftFixMaster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slave_RepShiftFixMaster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slave_ReqVerifyConfigFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Master_ReqVerifyConfigFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slave_RepVerifyConfigFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slave_UptConfigMd5); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS_CmdPrepareCloseServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SM_ReqPrepareCloseMyself); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS_CmdCloseServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2S_CmdUnloadServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netcluster_message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2M_ReqUnloadMyself); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_netcluster_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_netcluster_message_proto_goTypes,
		DependencyIndexes: file_netcluster_message_proto_depIdxs,
		MessageInfos:      file_netcluster_message_proto_msgTypes,
	}.Build()
	File_netcluster_message_proto = out.File
	file_netcluster_message_proto_rawDesc = nil
	file_netcluster_message_proto_goTypes = nil
	file_netcluster_message_proto_depIdxs = nil
}
