// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0
// 	protoc        v3.13.0
// source: netframe/message.proto

package netframe

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// extend message
type Server_Extend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId   uint32                    `protobuf:"varint,1,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	SessionId  uint64                    `protobuf:"varint,2,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	SeqId      int64                     `protobuf:"varint,3,opt,name=SeqId,proto3" json:"SeqId,omitempty"` // s/s 内部服务间RPC 序列号
	UserId     uint64                    `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ExtParam   int64                     `protobuf:"varint,5,opt,name=ExtParam,proto3" json:"ExtParam,omitempty"` //扩展参数
	RouterMeta *Server_Extend_RouterMeta `protobuf:"bytes,6,opt,name=routerMeta,proto3" json:"routerMeta,omitempty"`
	Account    string                    `protobuf:"bytes,7,opt,name=account,proto3" json:"account,omitempty"`
	ClientData []byte                    `protobuf:"bytes,8,opt,name=clientData,proto3" json:"clientData,omitempty"` // c/s  客户端生成的协议序列号，原样返回
}

func (x *Server_Extend) Reset() {
	*x = Server_Extend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netframe_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server_Extend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Extend) ProtoMessage() {}

func (x *Server_Extend) ProtoReflect() protoreflect.Message {
	mi := &file_netframe_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Extend.ProtoReflect.Descriptor instead.
func (*Server_Extend) Descriptor() ([]byte, []int) {
	return file_netframe_message_proto_rawDescGZIP(), []int{0}
}

func (x *Server_Extend) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *Server_Extend) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Server_Extend) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *Server_Extend) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Server_Extend) GetExtParam() int64 {
	if x != nil {
		return x.ExtParam
	}
	return 0
}

func (x *Server_Extend) GetRouterMeta() *Server_Extend_RouterMeta {
	if x != nil {
		return x.RouterMeta
	}
	return nil
}

func (x *Server_Extend) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Server_Extend) GetClientData() []byte {
	if x != nil {
		return x.ClientData
	}
	return nil
}

// heart
type Server_ReqHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp int64 `protobuf:"varint,1,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *Server_ReqHeartBeat) Reset() {
	*x = Server_ReqHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netframe_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server_ReqHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_ReqHeartBeat) ProtoMessage() {}

func (x *Server_ReqHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_netframe_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_ReqHeartBeat.ProtoReflect.Descriptor instead.
func (*Server_ReqHeartBeat) Descriptor() ([]byte, []int) {
	return file_netframe_message_proto_rawDescGZIP(), []int{1}
}

func (x *Server_ReqHeartBeat) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type Server_RespHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp int64 `protobuf:"varint,1,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
}

func (x *Server_RespHeartBeat) Reset() {
	*x = Server_RespHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netframe_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server_RespHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_RespHeartBeat) ProtoMessage() {}

func (x *Server_RespHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_netframe_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_RespHeartBeat.ProtoReflect.Descriptor instead.
func (*Server_RespHeartBeat) Descriptor() ([]byte, []int) {
	return file_netframe_message_proto_rawDescGZIP(), []int{2}
}

func (x *Server_RespHeartBeat) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

// client->server 注册
type Server_ReqRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientType      uint32 `protobuf:"varint,1,opt,name=ClientType,proto3" json:"ClientType,omitempty"`
	ClientId        uint32 `protobuf:"varint,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	ClientStartTime int64  `protobuf:"varint,3,opt,name=ClientStartTime,proto3" json:"ClientStartTime,omitempty"`
}

func (x *Server_ReqRegister) Reset() {
	*x = Server_ReqRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netframe_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server_ReqRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_ReqRegister) ProtoMessage() {}

func (x *Server_ReqRegister) ProtoReflect() protoreflect.Message {
	mi := &file_netframe_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_ReqRegister.ProtoReflect.Descriptor instead.
func (*Server_ReqRegister) Descriptor() ([]byte, []int) {
	return file_netframe_message_proto_rawDescGZIP(), []int{3}
}

func (x *Server_ReqRegister) GetClientType() uint32 {
	if x != nil {
		return x.ClientType
	}
	return 0
}

func (x *Server_ReqRegister) GetClientId() uint32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Server_ReqRegister) GetClientStartTime() int64 {
	if x != nil {
		return x.ClientStartTime
	}
	return 0
}

// server->client
type Server_RespRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerType      uint32 `protobuf:"varint,1,opt,name=ServerType,proto3" json:"ServerType,omitempty"`
	ServerId        uint32 `protobuf:"varint,2,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	ServerStartTime int64  `protobuf:"varint,3,opt,name=ServerStartTime,proto3" json:"ServerStartTime,omitempty"`
}

func (x *Server_RespRegister) Reset() {
	*x = Server_RespRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netframe_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server_RespRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_RespRegister) ProtoMessage() {}

func (x *Server_RespRegister) ProtoReflect() protoreflect.Message {
	mi := &file_netframe_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_RespRegister.ProtoReflect.Descriptor instead.
func (*Server_RespRegister) Descriptor() ([]byte, []int) {
	return file_netframe_message_proto_rawDescGZIP(), []int{4}
}

func (x *Server_RespRegister) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *Server_RespRegister) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *Server_RespRegister) GetServerStartTime() int64 {
	if x != nil {
		return x.ServerStartTime
	}
	return 0
}

// client->server 取消注册
type Server_ReportUnRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerStartTime int64 `protobuf:"varint,1,opt,name=ServerStartTime,proto3" json:"ServerStartTime,omitempty"`
}

func (x *Server_ReportUnRegister) Reset() {
	*x = Server_ReportUnRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netframe_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server_ReportUnRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_ReportUnRegister) ProtoMessage() {}

func (x *Server_ReportUnRegister) ProtoReflect() protoreflect.Message {
	mi := &file_netframe_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_ReportUnRegister.ProtoReflect.Descriptor instead.
func (*Server_ReportUnRegister) Descriptor() ([]byte, []int) {
	return file_netframe_message_proto_rawDescGZIP(), []int{5}
}

func (x *Server_ReportUnRegister) GetServerStartTime() int64 {
	if x != nil {
		return x.ServerStartTime
	}
	return 0
}

type Client_ReqHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp int64 `protobuf:"varint,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *Client_ReqHeartBeat) Reset() {
	*x = Client_ReqHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netframe_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client_ReqHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_ReqHeartBeat) ProtoMessage() {}

func (x *Client_ReqHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_netframe_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_ReqHeartBeat.ProtoReflect.Descriptor instead.
func (*Client_ReqHeartBeat) Descriptor() ([]byte, []int) {
	return file_netframe_message_proto_rawDescGZIP(), []int{6}
}

func (x *Client_ReqHeartBeat) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type Client_RespHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp int64 `protobuf:"varint,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *Client_RespHeartBeat) Reset() {
	*x = Client_RespHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netframe_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client_RespHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_RespHeartBeat) ProtoMessage() {}

func (x *Client_RespHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_netframe_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_RespHeartBeat.ProtoReflect.Descriptor instead.
func (*Client_RespHeartBeat) Descriptor() ([]byte, []int) {
	return file_netframe_message_proto_rawDescGZIP(), []int{7}
}

func (x *Client_RespHeartBeat) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

type Server_Extend_RouterMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqFrom uint32 `protobuf:"varint,1,opt,name=reqFrom,proto3" json:"reqFrom,omitempty"` // req 的发起者 svrID
}

func (x *Server_Extend_RouterMeta) Reset() {
	*x = Server_Extend_RouterMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_netframe_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server_Extend_RouterMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Extend_RouterMeta) ProtoMessage() {}

func (x *Server_Extend_RouterMeta) ProtoReflect() protoreflect.Message {
	mi := &file_netframe_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Extend_RouterMeta.ProtoReflect.Descriptor instead.
func (*Server_Extend_RouterMeta) Descriptor() ([]byte, []int) {
	return file_netframe_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Server_Extend_RouterMeta) GetReqFrom() uint32 {
	if x != nil {
		return x.ReqFrom
	}
	return 0
}

var File_netframe_message_proto protoreflect.FileDescriptor

var file_netframe_message_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6e, 0x65, 0x74, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x65, 0x74, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x22, 0xb9, 0x02, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x45, 0x78,
	0x74, 0x65, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x53, 0x65, 0x71, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53,
	0x65, 0x71, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x45, 0x78, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x45, 0x78, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x42, 0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e,
	0x65, 0x74, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x26, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x46, 0x72, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x65, 0x71, 0x46, 0x72, 0x6f, 0x6d, 0x22, 0x33,
	0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x52, 0x65, 0x71, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x22, 0x34, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x52, 0x65,
	0x73, 0x70, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x7a, 0x0a, 0x12, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x52, 0x65, 0x71, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x7b, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x43, 0x0a, 0x17, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x28, 0x0a,
	0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x52, 0x65, 0x71, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x34, 0x0a, 0x14,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x42, 0x65, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_netframe_message_proto_rawDescOnce sync.Once
	file_netframe_message_proto_rawDescData = file_netframe_message_proto_rawDesc
)

func file_netframe_message_proto_rawDescGZIP() []byte {
	file_netframe_message_proto_rawDescOnce.Do(func() {
		file_netframe_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_netframe_message_proto_rawDescData)
	})
	return file_netframe_message_proto_rawDescData
}

var file_netframe_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_netframe_message_proto_goTypes = []interface{}{
	(*Server_Extend)(nil),            // 0: netframe.Server_Extend
	(*Server_ReqHeartBeat)(nil),      // 1: netframe.Server_ReqHeartBeat
	(*Server_RespHeartBeat)(nil),     // 2: netframe.Server_RespHeartBeat
	(*Server_ReqRegister)(nil),       // 3: netframe.Server_ReqRegister
	(*Server_RespRegister)(nil),      // 4: netframe.Server_RespRegister
	(*Server_ReportUnRegister)(nil),  // 5: netframe.Server_ReportUnRegister
	(*Client_ReqHeartBeat)(nil),      // 6: netframe.Client_ReqHeartBeat
	(*Client_RespHeartBeat)(nil),     // 7: netframe.Client_RespHeartBeat
	(*Server_Extend_RouterMeta)(nil), // 8: netframe.Server_Extend.RouterMeta
}
var file_netframe_message_proto_depIdxs = []int32{
	8, // 0: netframe.Server_Extend.routerMeta:type_name -> netframe.Server_Extend.RouterMeta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_netframe_message_proto_init() }
func file_netframe_message_proto_init() {
	if File_netframe_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_netframe_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server_Extend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netframe_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server_ReqHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netframe_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server_RespHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netframe_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server_ReqRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netframe_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server_RespRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netframe_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server_ReportUnRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netframe_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client_ReqHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netframe_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client_RespHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_netframe_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server_Extend_RouterMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_netframe_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_netframe_message_proto_goTypes,
		DependencyIndexes: file_netframe_message_proto_depIdxs,
		MessageInfos:      file_netframe_message_proto_msgTypes,
	}.Build()
	File_netframe_message_proto = out.File
	file_netframe_message_proto_rawDesc = nil
	file_netframe_message_proto_goTypes = nil
	file_netframe_message_proto_depIdxs = nil
}
